Re-add full SPT build steps

diff --git a/.github/workflows/build-sharp.yaml b/.github/workflows/build-sharp.yaml
--- a/.github/workflows/build-sharp.yaml
+++ b/.github/workflows/build-sharp.yaml
@@ -24,7 +24,7 @@ jobs:
       build_type: ${{ steps.determine-build-type.outputs.build_type }}
       client_version: ${{ steps.versions.outputs.client_version }}
       spt_version: ${{ steps.versions.outputs.spt_version }}
-      platform: 'LINUX-X64'
+      platform: 'linux-x64'
 
     steps:
       - name: Determine Build Context
@@ -76,7 +76,7 @@ jobs:
         run: |
           PROCEED="true"
           TAG="${{ steps.determine-context.outputs.target_tag }}"
-          REPOS=("https://github.com/sp-tarkov/server-csharp.git")
+          REPOS=("https://github.com/sp-tarkov/server-csharp.git" "https://github.com/sp-tarkov/modules.git" "https://github.com/sp-tarkov/launcher.git")
           for REPO in "${REPOS[@]}"; do
             echo "Checking for tag $TAG in $REPO..."
             if ! git ls-remote --tags $REPO $TAG | grep -q $TAG; then
@@ -170,6 +170,112 @@ jobs:
           overwrite: true
           if-no-files-found: error
 
+  build-modules:
+    needs: prepare
+    if: needs.prepare.outputs.proceed == 'true'
+    runs-on: ubuntu-latest
+    container:
+      image: refringe/spt-build-dotnet:2.0.2
+    steps:
+      - name: Clone Modules
+        id: clone-modules
+        shell: bash
+        run: |
+          rm -rf /workspace/SPT/Build/modules
+
+          TAG=${{ needs.prepare.outputs.target_tag }}
+          echo "Cloning modules from tag $TAG"
+          git clone https://github.com/sp-tarkov/modules.git --branch "$TAG" --depth 1 /workspace/SPT/Build/modules
+
+          cd /workspace/SPT/Build/modules
+          echo "modules_commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+
+      - name: Download Client Module Package
+        shell: bash
+        run: |
+          DIR_MANAGED="/workspace/SPT/Build/modules/project/Shared/Managed"
+          DOWNLOAD_PATH="$DIR_MANAGED/${{ needs.prepare.outputs.client_version }}.7z"
+          DOWNLOAD_URL="${{ secrets.MODULE_DOMAIN }}/${{ needs.prepare.outputs.client_version }}.7z"
+          echo "Downloading Client Module Package from $DOWNLOAD_URL to $DOWNLOAD_PATH"
+          mkdir -p "$DIR_MANAGED"
+          wget -q -O "$DOWNLOAD_PATH" "$DOWNLOAD_URL" || {
+            echo "Failed to download the module package."
+            exit 1
+          }
+          if [ ! -s "$DOWNLOAD_PATH" ]; then
+            echo "The module package does not exist or is empty."
+            exit 1
+          fi
+          echo "Download Successful: $DOWNLOAD_PATH"
+
+      - name: Decompress Client Module Package
+        shell: bash
+        run: |
+          cd /workspace/SPT/Build/modules/project/Shared/Managed
+          7z x ${{ needs.prepare.outputs.client_version }}.7z -aoa
+          echo "Client module package decompressed."
+
+      - name: Delete Client Module Package
+        shell: bash
+        run: |
+          cd /workspace/SPT/Build/modules/project/Shared/Managed
+          rm -f ${{ needs.prepare.outputs.client_version }}.7z
+          echo "Client module package deleted."
+
+      - name: Build Modules
+        shell: bash
+        run: |
+          cd /workspace/SPT/Build/modules/project
+          dotnet build -c Release -p:Version=${{ needs.prepare.outputs.spt_version }}
+          printf "\nBuilt!\n\n"
+
+      - name: Upload Modules Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: modules-artifact
+          path: /workspace/SPT/Build/modules/project/Build
+          compression-level: 0
+          retention-days: 1
+          overwrite: true
+          if-no-files-found: error
+
+  build-launcher:
+    needs: prepare
+    if: needs.prepare.outputs.proceed == 'true'
+    runs-on: ubuntu-latest
+    container:
+      image: refringe/spt-build-dotnet:2.0.2
+    steps:
+      - name: Clone Launcher
+        id: clone-launcher
+        shell: bash
+        run: |
+          rm -rf /workspace/SPT/Build/launcher
+
+          TAG=${{ needs.prepare.outputs.target_tag }}
+          echo "Cloning launcher from tag $TAG"
+          git clone https://github.com/sp-tarkov/launcher.git --branch "$TAG" --depth 1 /workspace/SPT/Build/launcher
+
+          cd /workspace/SPT/Build/launcher
+          echo "launcher_commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+
+      - name: Build Launcher
+        shell: bash
+        run: |
+          cd /workspace/SPT/Build/launcher/project
+          dotnet build
+          printf "\nBuilt!\n\n"
+
+      - name: Upload Launcher Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: launcher-artifact
+          path: /workspace/SPT/Build/launcher/project/Build
+          compression-level: 0
+          retention-days: 1
+          overwrite: true
+          if-no-files-found: error
+
   assemble-and-publish:
     needs: [prepare, build-server]
     runs-on: ubuntu-latest
@@ -188,6 +294,22 @@ jobs:
           name: server-artifact
           path: release/
 
+      - name: Download Launcher Artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: launcher-artifact
+          path: release/
+
+      - name: Clone Build Project
+        uses: actions/checkout@v4
+        with:
+          repository: sp-tarkov/build
+          path: build
+
+      - name: Merge Static Assets and Dynamic Files
+        shell: bash
+        run: cp -rvf build/static-assets-csharp/. release/
+
       - name: Clone Build Project
         uses: actions/checkout@v4
         with:
@@ -205,19 +327,20 @@ jobs:
           BUILD_TYPE=${{ needs.prepare.outputs.build_type }}
           SPT_VERSION=${{ needs.prepare.outputs.spt_version }}
           CLIENT_VERSION=${{ needs.prepare.outputs.client_version }}
-          PLATFORM=${{ needs.prepare.outputs.platform }}
+          UPPER_PLATFORM=$(echo "${{ needs.prepare.outputs.platform }}" | tr '[:lower:]' '[:upper:]')
           SERVER_COMMIT=${{ needs.build-server.outputs.server_commit }}
           TARGET_TAG=${{ needs.prepare.outputs.target_tag }}
           DATE=$(date +%Y%m%d)
 
           if [[ "${{ needs.prepare.outputs.is_nightly }}" == "true" ]]; then
-            BASE_NAME="SPT-SERVER-NIGHTLY-${PLATFORM}-${SPT_VERSION}-${CLIENT_VERSION}-${SERVER_COMMIT}-${DATE}"
+            BASE_NAME="SPT-NIGHTLY-${UPPER_PLATFORM}-${SPT_VERSION}-${CLIENT_VERSION}-${SERVER_COMMIT}-${DATE}"
           else
             UPPER_BUILD_TYPE=$(echo "$BUILD_TYPE" | tr '[:lower:]' '[:upper:]')
             UPPER_TARGET_TAG=$(echo "$TARGET_TAG" | tr '[:lower:]' '[:upper:]')
+            
 
             if [ "$BUILD_TYPE" = "RELEASE" ]; then
-              BASE_NAME="SPT-SERVER-${PLATFORM}-${SPT_VERSION}-${CLIENT_VERSION}-${SERVER_COMMIT}"
+              BASE_NAME="SPT-${UPPER_PLATFORM}-${SPT_VERSION}-${CLIENT_VERSION}-${SERVER_COMMIT}"
             else
               TAG_PART=""
               if [[ "$UPPER_TARGET_TAG" == *-*-* ]]; then
@@ -227,9 +350,9 @@ jobs:
                 fi
               fi
               if [ -n "$TAG_PART" ]; then
-                BASE_NAME="SPT-SERVER-${PLATFORM}-${UPPER_BUILD_TYPE}-${SPT_VERSION}-${CLIENT_VERSION}-${SERVER_COMMIT}${TAG_PART}"
+                BASE_NAME="SPT-${UPPER_PLATFORM}-${UPPER_BUILD_TYPE}-${SPT_VERSION}-${CLIENT_VERSION}-${SERVER_COMMIT}${TAG_PART}"
               else
-                BASE_NAME="SPT-SERVER-${PLATFORM}-${UPPER_BUILD_TYPE}-${SPT_VERSION}-${CLIENT_VERSION}-${SERVER_COMMIT}-${DATE}"
+                BASE_NAME="SPT-${UPPER_PLATFORM}-${UPPER_BUILD_TYPE}-${SPT_VERSION}-${CLIENT_VERSION}-${SERVER_COMMIT}-${DATE}"
               fi
             fi
           fi
